### ISSUE TITLE
Crash when checking TerraformState

### ISSUE THREAD

**Issue by cartman09** [Xjph/EliteObservatory#1]
Hi,

I made the following custom file to check for terraformability:

`<ObservatoryCriteria>
  <Criteria Comparator="Equal" Value="1">
    <Operation Operator="Multiply">
      <FirstValue Type="EventData">TerraformState</FirstValue>
      <SecondValue Type="Number">1</SecondValue>
    </Operation>
    <Description>Terraformable</Description>
  </Criteria>
</ObservatoryCriteria>`

It crashes because the scanEvent.TerraformState is sometimes null.

Relevant lines:
https://github.com/Xjph/EliteObservatory/blob/83f714af9093ce2a06f6f0e74c83cef8663d8d36/Observatory/UserInterest.cs#L238

https://github.com/Xjph/EliteObservatory/blob/83f714af9093ce2a06f6f0e74c83cef8663d8d36/Observatory/UserInterest.cs#L114

**Comment by Xjph** [comment]
Fixed in commit 5ea2e59759bc57de28a144656bd22f96ba4031a4

**Comment by Xjph** [comment]
And released.

https://github.com/Xjph/EliteObservatory/releases/tag/v0.3.19.256
