### ISSUE TITLE
Trigger alert on specific atmospheric parameters

### ISSUE THREAD

**Issue by RedfoxCh** [Xjph/EliteObservatory#11]
Trigger alert on specific atmospheric parameters.

Pseudo-code example of what I'd be using it for: 
Alert if (
planetType = Any Type of Gas Giant AND
planetType != Helium-rich Gas Giant AND
**Atmosphere Helium Percentage > 30**
)

**Comment by Xjph** [comment]
Fun fact, this was added in commit 13852c7, has been available since v0.5.20.067, and I completely forgot that I added.

I'll add it to the documentation. :P

**Comment by RedfoxCh** [comment]
Lovely, thanks!

Do you have a config lying around from testing? If not I'll try to figure it out.

**Comment by Xjph** [comment]
I do not, but if you need any help with it I'll be happy to oblige.
