### ISSUE TITLE
Possible to disable or configure >1EM?

### ISSUE THREAD

**Issue by Slegnor** [Xjph/EliteObservatory#19]
Hi, is it possible to disable the >1EM notification or configure it to allow greater sizes (ie >5EM, >10EM etc)?
there are a lot of bodies >1EM and the message playing regularly gets old fast :P

**Comment by Xjph** [comment]
Do you mean the >1 EM and tidal lock sample custom criteria? Yes, you can disable custom criteria or edit the criteria XML file which should be in the same folder as the exe.

**Comment by Slegnor** [comment]
Ah, i see, didn't realise they were in the XMl, thanks
