### ISSUE TITLE
Cannot find Journal path when Saved Games folder has been redirected from user profile path

### ISSUE THREAD

**Issue by sviper7** [Xjph/EliteObservatory#25]
Hello, this is the same issue as issue #21 "Have to select journal location every launch", but the fix for that did not fix the underlying problem, which is that the file explorer silently redirects requests to the expected location of the folder (ie "C:\users\<username>\Saved Games" to the new location (such as "D:\Something\Saved Games".  Since it is not immediately obvious to even a user that has redirected the path themselves that this is happening (I'd forgotten I'd done it), I think perhaps the correct fix for this is to use the P/Invoke method SHGetKnownFolderPath (for an example see https://stackoverflow.com/questions/3795023/how-to-programmatically-derive-windows-downloads-folder-userprofile-downloads/3795159#3795159 for an example, replacing the GUID with the one for FOLDERID_SavedGames
from https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid
This then correctly gets the real path to the Saved Games folder.

**Comment by Xjph** [comment]
Sounds good to me, I'll have this in the next release.

**Comment by sviper7** [comment]
Great, thanks.  Happy to test the change on my system before release if you like.

**Comment by Xjph** [comment]
Heh, thanks for the offer, but I'm doing a release today already. 

Feel free to test it though!

Completed on commit 13852c7086e1e31b8c4fa8db007e6c3b3ffd54f6
