### ISSUE TITLE
Add Critera for Human/Thargoind/Guardian/Other signals?

### ISSUE THREAD

**Issue by Slegnor** [Xjph/EliteObservatory#35]
Is it possible to add criteria for when Human/Thargoind/Guardian/Other signals are detected on a body?

**Comment by Xjph** [comment]
Unfortunately no. Not from the FSS scan at least. Surface signal information isn't written to the journal until the DSS scan is completed when you probe the body.

Reading the DSS scan results for the signals and logging those is possible of course, but notifying about the signals at that point seems a little redundant.

All that said, the custom criteria system in the rewrite should be a lot easier to use and more flexible, so if that's something you want it might be doable then.

**Comment by Slegnor** [comment]
That's a shame, but you're right, once FSS scanned it doesn't make sense to have it repeat the info as late on as the DSS stage
