### ISSUE TITLE
What about "all jumponium materials in system"

### ISSUE THREAD

**Issue by dylan-k** [Xjph/EliteObservatory#37]
This is maybe a dumb question, but when the voice says "all jumponium materials in system" -- what's the predicate of that sentence? I'm assuming it means "all jumponium materials in system have been scanned" is that correct? I have this same question for some of the other descriptions too. Thanks for helping a newbie here.

**Comment by Xjph** [comment]
All of the materials necessary for premium FSD synthesis (colloquially: jumponium) have been found in system. Known as a "green" system on EDSM.

Feel free to ask any other questions you have.

**Comment by dylan-k** [comment]
So, just to be super sure I understand... It means "this system contains all of the materials you need for premium synthesis" correct? On the other hand it could just mean that you've found everything that can be found, but maybe not everything required.

**Comment by Xjph** [comment]
It's the first one. If it was the second then every system would trigger it, and it would require impossible information on the things in system you haven't scanned yet.

**Comment by dylan-k** [comment]
Yes that makes sense. Thank you :)
