### ISSUE TITLE
Suggestion to Add a Github Topic

### ISSUE THREAD

**Issue by dylan-k** [Xjph/EliteObservatory#38]
Github has a tags feature that I've found to be quite useful for finding [repos related to Elite Dangerous](https://github.com/topics/elite-dangerous). I noticed that this one might benefit from adding the `elite-dangerous` tag. Github calls them topics and says: To associate your repository with the elite-dangerous topic, visit your repo's landing page and select "manage topics." You can [add a screenshot/preview image](https://docs.github.com/en/github/administering-a-repository/customizing-your-repositorys-social-media-preview) that will show up there as well.

I'm having fun getting to know this project, and hope this would help others to do so as well.

**Comment by Xjph** [comment]
Done. Will do the same for [Observatory Core](https://github.com/Xjph/ObservatoryCore) as well.
