### ISSUE TITLE
Regular "Landable with Atmosphere?!" message now Odyssey is out

### ISSUE THREAD

**Issue by Slegnor** [Xjph/EliteObservatory#39]
Wording of "Landable with Atmosphere?!" message is now kind of redundant.
I know this will be related to the changes with Odyssey but just thought it better to log it rather than not, as these will be the new norm not a galactic anomaly, even just removing the ?! might be enough?

**Comment by Xjph** [comment]
Fixed in release [v0.5.21.144](https://github.com/Xjph/EliteObservatory/releases/tag/v0.5.21.144).
