### ISSUE TITLE
Can Elite Observatory List Planets with Biological Signals?

### ISSUE THREAD

**Issue by dylan-k** [Xjph/EliteObservatory#42]
I noticed in a recent journal file that there is a log whenever a planet turns out to have one or more biological signals. I had hoped to write a custom criteria so that Elite Observatory could list these for me as it does with other interesting findings, but I don't think it is supported yet. Is it possible?

**Comment by dylan-k** [comment]
fwiw here's an example of a relevant line from a journal

```
{ "timestamp":"2021-08-04T21:30:09Z", "event":"FSSBodySignals", "BodyName":"Groeh HC-D d12-0 B 4 a", "BodyID":13, "SystemAddress":10863248747, "Signals":[ { "Type":"$SAA_SignalType_Biological;", "Type_Localised":"Biological", "Count":1 } ] }
```

**Comment by Xjph** [comment]
This is definitely something that can be done now, but not here. Going forward, any new features are going to happen in [ObservatoryCore](https://github.com/Xjph/ObservatoryCore) or its plugins (in this case, [ObservatoryExplorer](https://github.com/Xjph/ObservatoryExplorer)).

I'll open an issue there and reference this one for you.
