### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by dylan-k** [Xjph/EliteObservatory#43]
Can the app respond to Windows settings for Dark Mode, or otherwise use a dark theme? Most of the apps I use with Elite Dangerous can use a dark theme and it works well for me playing at night.

**Comment by Xjph** [comment]
This won't be done in the original elite observatory. However, the Observatory Core rewrite actually _only_ has a dark mode, with a light mode as a planned future feature, so that might be more to your taste!

https://github.com/Xjph/ObservatoryCore/releases
