### ISSUE TITLE
Export To File

### ISSUE THREAD

**Issue by Xjph** [Xjph/EliteObservatory#5]
Add ability to export current list to a file. Probably tab-delimited text?

**Comment by Elite-IGAU** [comment]
CSV or JSON -  Would be nice if it passed the data straight from the journal to the export file, unmolested.

**Comment by Xjph** [comment]
Was thinking tab-delimited as commas show up semi-regularly in the text shown in the list. This was planned to be a simple dump of the list itself, not the backing data that generated it.

When you say "data straight from the journal file", so you mean the original numbers with full precision, or the full original line from the journal?  If the latter that should be covered by #6.

That said, multiple export options won't be too difficult to implement. Formatted, full precision, and full journal exports are all doable. I'm not trying to push back on your request here, just want to get a better feel for what exactly you need.

**Comment by Elite-IGAU** [comment]
Yeah, basically #6. Something like "export journal entries"

**Comment by Xjph** [comment]
This is probably one of the more asked for features. Bumping it up, knocking it out. Commit 24fdd6f

Look for it in a release soon.

**Comment by Xjph** [comment]
And released.
